language: node_js
sudo: false
node_js:
- '0.12'
- '0.11'
- '0.10'
before_install:
- cp ci/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
- cp ci/npm-config.sh $HOME/
- chmod +x $HOME/npm-config.sh
- $HOME/travis-ci.sh before-install
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
- $HOME/travis-ci.sh before-deploy
- cd built
after_deploy:
- $HOME/travis-ci.sh after-deploy
cache:
  directories:
  - node_modules
notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalamuna.com
    - ben@kalamuna.com
    on_success: always
env:
  global:
  - secure: CSzY3hpnoI4FI1JcoBmHXcMCIFM0gfzME4RntPdV13tfIPh4UaG/1NfOjZJy/Uyhm18CLjIy0YDK52TbL4JOZZWDogipPmh+wzBsa90WbJMGEyG4FxOyYGfxjeq/FBWUDGYQdbaJVsJ0YgPW2NKN5hEHLvn04+d7i4oBSR8sGdC3Ne4XoCSlypjOoE9aieAua3bgqmzsPR/N5IkrCTteJr4UqHUcJ8C70+jimUHlb/Wzd3e45Z5Czo3NTtgexbsw90Z1+zyn39phQPnXBjXjk0bJJn1XaFYb3DbzsomPBt1/HHBRqrw933iW57UDu3YrLqjonhcuE94cEsNtHLzWkTOxRTmZR+pWhFGTHSDvmUToJDJIqQ+0XuPLUU0ZobjkAUIhe6TMEfNMg2tV3qyL4is5F2rs8/APtpxyWmttyhi2FRXHFjdZzlVG9SsMG8zbj0mLbxcQeAfcyLnAmmXzMyvSmZDldowF8pEAIyM5UCkO6I46SazPPqPYd2wvICoJqcBz5BdwirV8y56p8duKoWscYixtQApM46fiM/E6fgDrwO2nR0eA6VhxshNb37vRmnaPE4y35imedzFLlOUJIpdVwtBKvAUBoQo+GarxFXEd+MIVXD4SFNGX6uht1eGidnlxaSjkezbGUB7/BIntRTJpihaqeef7anLK4PVWU0I=
  - secure: nek4qkSRFvfIDNTW5z86C0Ba+UNu/iCFoy/50tAeQbOWUrzB0Wo8ppka7EuDoyBTHS3zW5qiuOhDMLSV/Q/9jyv7vYKyhoDiV3n4FBYM4d1fH96kC4FcHXhj0a5ykAi2ofMeRcS8y3CUfDY3Jb/FyutKDK8OXSKDegk5O08uhgQhdUHXsVyHe+OrwSw42OwIk35VsWYmzCWixPzFTStZQezPjZlSUpbgVlquUNDP682OsOnFi4RBGhzBXVARJQilb26VEIXcTsPVADVGlxynIgwkE7W9KfjyI0un01CHAUlMrzavruuaJjUw5ec6l8oZFGb3aAWybFnaS6fGiXvdSozoq9KjmJtIkbDZFxKjLK2vD3dTxz1crP0QD+pCtDWUDjkkq5oF1uovC1AnmbAIxNZotQ0yIpIiwI+c2f+iGD4NRas94c61DsVbfp98fK5s3Zw+Jl65PqZbVutOHirqs91ly4+21Xxs92AbZegfJLaat47q2qhe5HDgoOE0MJ4WwL3Z3O5sLg8waxBBxR5K74eVySoOl2tb90Psa0KW36mslyo1Mmyyj+8q2vSE+zTTdFMVSvewZk4J/NKjgqDoZz75WTRNF7ttqOqOBJhb+sGCvL5YjAym96jjFrnqrCYGQDo+xkqwesx/EdtnUQCu4FJFZgBWuuaCu3Zm0ZEYcog=
  - secure: VKaQRX15Hifklny8eseQhS2vOLkq8MZ+dAUtF0DTOoQ9AkO41paUOP0MqI+aTrS8RnJjud4Qbj/BnJgj5YHxPoGUiwyE7HjklJMfVqkypRFnAvM+XK3k63dX+QsBmxScT+79mxsa1x0McnU4lIgbJB2eYmzL6gxt3bKX2EU2E5YxisBlmGvzL8Lc0egbutuEdSfBk8F8Ie3rZDscvZYDJ3bZKNU+51OzfmI2TLF1t9Q0+fUA+mnsV6vg8hQila0kshqTwfxVU+k1HNg13tDIc+HkL92Cmx6Mrrsb2oQls/R8sZbI9dbRIViJhYsXKH5sZzmJZjB59tVI58lrWaF9l0NkPUCs1R+iAK5+lZIZrfbw1GL6cTXo3qtMXmMmJUIBcBW0Pf328r2s7b3qtf8+3UR99XNpee927XteN20fENye7Rh6j11N6WYCceeyepDf8DeXwaqalG+kGHiChwXJuy7Gd91n1mciaLiMplH9A+zZE5O6T7UA5Mx1n75QMoASk89ucNqDH7JQ4P7UcJK5sfzGinqzc8E7CcTL1XeMW8kCOgjbUjht0rhp0nJmtY+uUrmpUNOTJZN4QBPh5i8CMTq/J/XcPYhn4dtSNpLSgpx1PY9AgeZjuk/SWaHf/1MhfJD/y++ZWoAkHcpAKWg//rezbCMDZkKV3yp31lvbPvs=
